import type { CreateBlueprint } from "@paperclipai/shared";

/**
 * Pre-built Blueprint definitions shipped with Paperclip.
 * These are inserted on first use or via a seed route.
 */
export const CINEMATIC_HERO_BLUEPRINT: CreateBlueprint = {
  slug: "cinematic-hero",
  title: "Cinematic Hero",
  description:
    "Crea un sito web con hero video cinematica (panoramica + vista esplosa scroll) usando Kling 3.0 via fal.ai. Costo stimato ~$4, tempo ~15 minuti.",
  category: "web-design",
  icon: "\uD83C\uDFAC",
  version: "1.0.0",
  status: "published",
  estimatedCostCents: 400,
  estimatedDurationMinutes: 15,
  tags: ["video-ai", "landing-page", "kling", "fal.ai"],
  triggers: [
    "hero cinematico",
    "cinematic hero",
    "landing animata",
    "sito con video hero",
    "hero video",
  ],
  requiredSecrets: ["FAL_KEY"],
  requiredTools: ["ffmpeg", "claude-code"],
  defaultParams: {
    industry: "",
    businessDescription: "",
    style: "luxury",
  },
  steps: [
    {
      id: "input-brief",
      title: "Brief cliente",
      description: "Raccogli settore, descrizione business e stile preferito",
      order: 0,
      type: "input",
      auto: false,
      paramsSchema: {
        type: "object",
        properties: {
          industry: { type: "string", title: "Settore/industria" },
          businessDescription: { type: "string", title: "Descrizione business (2-3 frasi)" },
          style: {
            type: "string",
            title: "Stile",
            enum: ["luxury", "minimal", "bold", "warm"],
            default: "luxury",
          },
        },
        required: ["industry", "businessDescription"],
      },
      outputType: "text",
    },
    {
      id: "design-base",
      title: "Design sito base",
      description: "Genera sito HTML statico completo con design premium one-shot",
      order: 1,
      type: "generate",
      provider: "claude-code",
      auto: true,
      outputType: "html",
      costEstimateCents: 75,
      maxRetries: 2,
    },
    {
      id: "review-design",
      title: "Review design",
      description: "Valida il design base prima di procedere con i video",
      order: 2,
      type: "review",
      auto: false,
      dependsOn: ["design-base"],
    },
    {
      id: "gen-video-hero",
      title: "Video hero (panoramico)",
      description:
        "Genera video panoramico 3D per hero background (5s, 16:9, 1080p) con Kling 3.0 via fal.ai",
      order: 3,
      type: "generate",
      provider: "kling-fal",
      auto: true,
      outputType: "video",
      costEstimateCents: 84,
      maxRetries: 3,
      variants: 3,
      dependsOn: ["review-design"],
    },
    {
      id: "gen-video-scroll",
      title: "Video scroll (vista esplosa)",
      description:
        "Genera video vista esplosa per scroll animation (5s, 16:9, 1080p) con Kling 3.0 via fal.ai",
      order: 4,
      type: "generate",
      provider: "kling-fal",
      auto: true,
      outputType: "video",
      costEstimateCents: 84,
      maxRetries: 3,
      variants: 3,
      dependsOn: ["review-design"],
    },
    {
      id: "choose-variants",
      title: "Scegli varianti video",
      description: "Seleziona le varianti migliori per hero e scroll",
      order: 5,
      type: "review",
      auto: false,
      dependsOn: ["gen-video-hero", "gen-video-scroll"],
    },
    {
      id: "integrate-hero",
      title: "Integrazione hero video",
      description:
        "Inserisci video hero nel sito con gradient overlay, centra hero, fix testo leggibilita",
      order: 6,
      type: "integrate",
      provider: "claude-code",
      auto: true,
      outputType: "html",
      costEstimateCents: 35,
      dependsOn: ["choose-variants"],
    },
    {
      id: "integrate-scroll",
      title: "Integrazione scroll animation",
      description:
        "Estrai frame JPEG, crea scroll sequence, aggiungi sezioni testo con reveal, gradient/overlay",
      order: 7,
      type: "integrate",
      provider: "claude-code",
      auto: true,
      outputType: "html",
      costEstimateCents: 35,
      dependsOn: ["choose-variants"],
    },
    {
      id: "optimize",
      title: "Ottimizzazione performance",
      description: "Comprimi video hero (<500KB), ottimizza frame JPEG, preload",
      order: 8,
      type: "integrate",
      provider: "claude-code",
      auto: true,
      outputType: "html",
      costEstimateCents: 15,
      dependsOn: ["integrate-hero", "integrate-scroll"],
    },
    {
      id: "review-final",
      title: "Review finale",
      description: "Verifica sito completo: fluidita scroll, leggibilita, performance",
      order: 9,
      type: "review",
      auto: false,
      dependsOn: ["optimize"],
    },
    {
      id: "deploy",
      title: "Deploy",
      description: "Pubblica su Netlify e ottimizza per mobile",
      order: 10,
      type: "deploy",
      provider: "netlify",
      auto: true,
      outputType: "url",
      costEstimateCents: 0,
      dependsOn: ["review-final"],
    },
  ],
};

export const BUILT_IN_BLUEPRINTS: CreateBlueprint[] = [CINEMATIC_HERO_BLUEPRINT];
